//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace AgenteServiciosPlanificacion.ServiciosWebGenericas
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiciosWebGenericas.IServiciosWebGenericasManager")]
    public interface IServiciosWebGenericasManager
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPArrayByte", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPArrayByteResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoArrayByte EjecutarSPArrayByte(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPArrayByte", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPArrayByteResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoArrayByte> EjecutarSPArrayByteAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDateTime", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDateTimeResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoDateTime EjecutarSPDateTime(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDateTime", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDateTimeResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoDateTime> EjecutarSPDateTimeAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDecimal", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDecimalResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoDecimal EjecutarSPDecimal(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDecimal", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPDecimalResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoDecimal> EjecutarSPDecimalAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPInt", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPIntResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoInt EjecutarSPInt(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPInt", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPIntResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoInt> EjecutarSPIntAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPJsonDocument", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPJsonDocumentResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoJsonDocument EjecutarSPJsonDocument(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPJsonDocument", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPJsonDocumentResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoJsonDocument> EjecutarSPJsonDocumentAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPString", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPStringResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoString EjecutarSPString(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPString", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPStringResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoString> EjecutarSPStringAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPXmlDocument", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPXmlDocumentResponse")]
        UVNetDTOs.DTOsGenericas.Resultado.CResultadoXmlDocument EjecutarSPXmlDocument(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPXmlDocument", ReplyAction = "http://tempuri.org/IServiciosWebGenericasManager/EjecutarSPXmlDocumentResponse")]
        System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoXmlDocument> EjecutarSPXmlDocumentAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosWebGenericasManagerChannel : AgenteServiciosPlanificacion.ServiciosWebGenericas.IServiciosWebGenericasManager, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosWebGenericasManagerClient : System.ServiceModel.ClientBase<AgenteServiciosPlanificacion.ServiciosWebGenericas.IServiciosWebGenericasManager>, AgenteServiciosPlanificacion.ServiciosWebGenericas.IServiciosWebGenericasManager
    {

        public ServiciosWebGenericasManagerClient()
        {
        }

        public ServiciosWebGenericasManagerClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServiciosWebGenericasManagerClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiciosWebGenericasManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServiciosWebGenericasManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoArrayByte EjecutarSPArrayByte(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPArrayByte(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoArrayByte> EjecutarSPArrayByteAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPArrayByteAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoDateTime EjecutarSPDateTime(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPDateTime(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoDateTime> EjecutarSPDateTimeAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPDateTimeAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoDecimal EjecutarSPDecimal(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPDecimal(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoDecimal> EjecutarSPDecimalAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPDecimalAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoInt EjecutarSPInt(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPInt(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoInt> EjecutarSPIntAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPIntAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoJsonDocument EjecutarSPJsonDocument(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPJsonDocument(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoJsonDocument> EjecutarSPJsonDocumentAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPJsonDocumentAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoString EjecutarSPString(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPString(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoString> EjecutarSPStringAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPStringAsync(lEParametros);
        }

        public UVNetDTOs.DTOsGenericas.Resultado.CResultadoXmlDocument EjecutarSPXmlDocument(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPXmlDocument(lEParametros);
        }

        public System.Threading.Tasks.Task<UVNetDTOs.DTOsGenericas.Resultado.CResultadoXmlDocument> EjecutarSPXmlDocumentAsync(UVNetDTOs.DTOsGenericas.Parametro.CEParametros[] lEParametros)
        {
            return base.Channel.EjecutarSPXmlDocumentAsync(lEParametros);
        }
    }
}
